kind: pipeline
type: docker
name: image-webapi
platform:
  os: linux
  arch: amd64

steps:

  - name: docker-build
    image: plugins/docker
    settings: 
      username: harbor账号
      password: harbor密码
      repo: gogs服务ip或域名:gogs服务端口/image-webapi/image-webapi
      registry: http://harbor服务ip或域名:harbor服务端口
      insecure: true
      privileged: true
      dockerfile: ./ImageWebApi/Dockerfile
      tags:
        - 'latest'

  - name: ssh-deploy
    image: appleboy/drone-ssh
    settings:
      insecure: true
      privileged: true
      host: 目标部署服务器ip或主机名
      port: 目标服务器的ssh端口
      username: 目标服务器用户名
      password: 目标服务器密码
      command_timeout: 3m
      script:
        - echo "harbor密码" | docker login -u harbor账号 --password-stdin harbor服务ip或主机名:harbor服务端口
        - docker pull harbor服务ip或主机名:harbor服务端口/image-webapi/image-webapi:latest
        - docker stop image-webapi || true
        - docker rm image-webapi || true
        - docker run -d --name image-webapi -p 10087:80 -v /home/app/image-webapi/Image:/app/Image -v /home/app/image-webapi/ImageCache:/app/ImageCache harbor服务ip或主机名:harbor服务端口/image-webapi/image-webapi:latest

trigger:
  branch:
    - main
  event:
    - push